import type { FeaturedProject, MiniProject } from "../types";

const GH = "https://github.com/vigneshwaran484";

/**
 * Featured builds. Each one is described in the order an interviewer
 * probes: problem -> approach -> concrete decisions -> status.
 * Every claim below was checked against the repo source on 2026-09-28.
 * Keep every sentence defensible out loud.
 */
export const featured: FeaturedProject[] = [
  {
    id: "jarvis-linux",
    name: "Jarvis-Linux",
    kind: "VOICE-DRIVEN DESKTOP AGENT",
    status: "in-progress",
    problem:
      "Desktop voice assistants either ship every request to a cloud model or stop at fixed intents. I wanted an agent that reasons over a task with a local LLM and actually operates my Linux desktop.",
    approach:
      "A ReAct loop over Llama 3.2 on Ollama picks from 26 system tools: apps, files, audio and brightness, system telemetry via psutil, screenshots, and Hyprland windows and workspaces via hyprctl. Memory has two tiers: a rolling 10-turn window and long-term semantic recall with FAISS over MiniLM embeddings, exposed to the model as remember, recall and forget tools. A Tkinter HUD mirrors a five-state machine (idle, listening, thinking, speaking, error).",
    decisions: [
      "Tools are called through a small text protocol (TOOL: name|args) that the loop parses. An unknown tool name goes back to the model with the list of valid tools so it can retry, instead of crashing the loop.",
      "Embeddings are L2-normalised so FAISS inner-product search is cosine similarity, and the heavy dependencies (faiss, sentence-transformers) load lazily so startup stays fast.",
      "Wake word and speech-to-text currently use Google STT with ambient-noise calibration. Moving to an offline engine (openWakeWord or Porcupine) is a one-file change behind the same blocking contract, and it is the next item on the list.",
    ],
    stack: ["Python", "Ollama", "Llama 3.2", "FAISS", "sentence-transformers", "psutil", "edge-tts", "Tkinter", "Hyprland"],
    role: "Solo project and a personal system, not a product. The LLM and memory run on-device; speech recognition and text-to-speech currently use online services. An earlier Windows build lives in a separate repo.",
    repo: `${GH}/Jarvis-Linux`,
  },
  {
    id: "task-manager",
    name: "Task Manager, DevSecOps",
    kind: "SECURE CI/CD PIPELINE",
    status: "complete",
    problem:
      "Security usually gets bolted onto student projects at the end, if at all. I wanted a small full-stack app where every commit is scanned and every deploy is tested before anyone relies on it.",
    approach:
      "A FastAPI + PostgreSQL backend (SQLAlchemy, Alembic) and a React front end, containerised and deployed to Azure Container Apps with Terraform. CI fails the build on Semgrep SAST findings, Gitleaks secrets across the full commit history, pip-audit and npm audit, and Trivy image scans. CD signs in to Azure over OIDC, applies Terraform, deploys images tagged with the commit SHA, and runs an OWASP ZAP baseline scan against the live URL.",
    decisions: [
      "GitHub Actions authenticates to Azure through OIDC federation, so no long-lived cloud credential is stored in the repository. The JWT signing secret is generated by Terraform and kept in Key Vault.",
      "Access tokens expire in 15 minutes and refresh tokens rotate on every use, so a stolen refresh token that gets used shows up as a failed refresh for the real user.",
      "Scans are merge gates, not reports. When a dependency advisory is accepted, it is an explicit ignore line in the workflow that a reviewer can see and question.",
    ],
    stack: ["FastAPI", "PostgreSQL", "React", "Docker", "GitHub Actions", "Terraform", "Azure", "Semgrep", "Gitleaks", "Trivy", "OWASP ZAP"],
    role: "Solo project, built while learning DevSecOps alongside coursework.",
    repo: `${GH}/task-manager`,
  },
  {
    id: "law-suite",
    name: "Law-Suite",
    kind: "MULTI-TENANT LEGAL SAAS",
    status: "in-progress",
    problem:
      "A 14-module legal practice platform where firms, partners, associates and clients need strictly different views of the same case data, with every sensitive action traceable.",
    approach:
      "React with Redux Toolkit and RTK Query on the front, Node.js/Express and PostgreSQL behind it. Authorization is a four-tier hierarchical RBAC model enforced in Express middleware before any handler runs. Auth uses short-lived JWT access tokens with rotating refresh tokens, bcrypt password hashing, a 6-digit OTP with a 5-minute expiry, and login rate limiting (5 attempts per 10 minutes). Sensitive mutations write to an append-only audit log.",
    decisions: [
      "RBAC checks live in middleware keyed on route metadata, not inside handlers, so a new endpoint cannot ship without an explicit permission declaration.",
      "Refresh-token rotation invalidates the previous token on every use; a reused token revokes the whole session family, which limits damage from a leaked refresh token.",
      "The audit log table has no UPDATE or DELETE grants for the application role, so immutability is enforced at the database level rather than by convention.",
    ],
    stack: ["React", "Redux Toolkit", "RTK Query", "Node.js", "Express", "PostgreSQL", "JWT", "bcrypt"],
    role: "Team project under a mentor. My role: API integration engineer, owning authentication, RBAC middleware and audit logging. Not sole author.",
    // TODO: add repo URL if/when the team repo is public
  },
  {
    id: "neuromotion",
    name: "NeuroMotion AI",
    kind: "BIOMECHANICAL MOTION ANALYSIS",
    status: "research",
    problem:
      "Form-correction tools compare your movement to a reference clip frame by frame, which breaks the moment you move at a different speed. The target case is the basketball free throw.",
    approach:
      "A FastAPI service runs MediaPipe Pose to extract 33 landmarks per frame and reduces them to six joint angles (elbow, shoulder, wrist, knee, hip, trunk lean). Dynamic Time Warping aligns the shot against an expert reference sequence built from professional players, independent of tempo. A ten-rule engine turns the aligned deviations into prioritised corrections and a skeleton heatmap at the frame of maximum deviation. A Flutter client captures video and shows scores, trends and session history.",
    decisions: [
      "Joint angles instead of raw landmark coordinates as the comparison signal: angles are invariant to scale and translation, which removes body-size and camera-distance effects before alignment.",
      "DTW over fixed-window comparison, so a slow shot and a fast shot of the same form align to the same reference phases.",
      "A rules engine rather than a learned classifier for diagnostics, so every flagged fault maps to a stated threshold that a coach can read and adjust.",
    ],
    stack: ["Python", "FastAPI", "MediaPipe", "NumPy", "DTW", "Flutter"],
    role: "Started as a team-of-four entry to the Unisys Innovation Program (UIP 17): abstract shortlisted, built with a Unisys mentor, out after round 2. The team has moved on and I'm continuing it solo toward a research paper and patent. Open question: whether the joint-angle and DTW comparison holds up across camera angles. Not yet validated.",
    repo: `${GH}/Neuromotion-AI`,
  },
];

/**
 * Compact grid. Only projects with a public repo that I can explain.
 */
export const more: MiniProject[] = [
  {
    name: "Email Threat Detector",
    tagline: "Smart India Hackathon 2026 entry. Scores .eml files using SPF, DKIM and DMARC checks, lookalike-domain detection (Levenshtein), phishing-language and URL analysis.",
    stack: ["FastAPI", "React", "Python"],
    repo: `${GH}/SIH2026`,
  },
  {
    name: "StreakForge",
    tagline: "Offline-first habit tracker PWA. Streaks are computed from an immutable check-in log; a service worker caches the shell for full offline use.",
    stack: ["JavaScript", "Vite", "PWA"],
    live: "https://streak-forge147.netlify.app",
    repo: `${GH}/Streak-Forge`,
  },
  {
    name: "Civic Pulse",
    tagline: "Gen AI Academy APAC hackathon build. Gemini classifies and scores citizen complaints, a statistical check flags 2x spikes per zone, and admins query in plain English.",
    stack: ["FastAPI", "Gemini", "PostgreSQL", "React"],
    repo: `${GH}/civic-pulse`,
  },
  {
    name: "Police Akka",
    tagline: "Citizen SOS app and police dashboard with Firebase real-time streams, live GPS and Groq-hosted legal guidance. Built during the ATRIBS internship.",
    stack: ["Flutter", "Firebase", "GPS", "Groq"],
    repo: `${GH}/police-akka-copy`,
  },
  {
    name: "Result Analysis",
    tagline: "Generates the seven university result forms from raw result workbooks. Recomputes GPA, CGPA and rankings from grade blocks instead of trusting sheet totals.",
    stack: ["FastAPI", "Pandas", "React"],
    repo: `${GH}/Result-Analysis`,
  },
  {
    name: "StadiumOps Copilot",
    tagline: "RAG assistant for stadium volunteer SOPs. Gemini embeddings, Groq generation, FAISS index.",
    stack: ["FastAPI", "Gemini", "Groq", "FAISS"],
    repo: `${GH}/stadium-ops-copilot`,
    live: "https://stadium-ops-copilot.onrender.com",
  },
  {
    name: "MiniNB",
    tagline: "Personal notes assistant: LLM auto-tagging, chat grounded only in your own notes, and action-item extraction.",
    stack: ["Python", "Streamlit", "Groq"],
    repo: `${GH}/MiniNB`,
  },
  {
    name: "DocuMind",
    tagline: "Document Q&A over uploaded PDFs with chunked retrieval.",
    stack: ["Python", "FastAPI", "Embeddings"],
    repo: `${GH}/DocuMind`,
    live: "https://documind-production-6c3b.up.railway.app/",
  },
  {
    name: "PillMatrix",
    tagline: "Multi-role healthcare workflow (doctors, patients, labs, pharmacies) with QR-based patient access and a Gemini prescription chatbot.",
    stack: ["Firebase", "Gemini", "React Native"],
    repo: `${GH}/PillMatrix`,
  },
];
